### ISSUE TITLE
Problemas con el despliegue

### ISSUE THREAD

**Issue by AlejandroGalanFreire** [Arquisoft/dede_es2a#185]
Llevamos varias semanas intentando desplegar la aplicación. En primer lugar decidimos realizarlo con heroku, nos daba problemas al no encontrar una dependencia, entonces decidimos intentarlo con AWS, y cuando parecía que ya estaba todo, una de las API (auth0) que utiliza nuestra aplicación nos da problemas de seguridad. Entonces, definitivamente decidimos volver al despliegue en heroku ya que aquí ya conseguimos tener la webapp en la nube, pero seguimos con el problema de la dependencia al desplegar el restapi. Es decir, creamos dos aplicaciones, una para webapp y otra para restapi, que se lanzan en heroku de manera independiente.
![image](https://user-images.githubusercontent.com/79645666/165732000-747e54cb-3778-42ad-bb46-9c778e28f57b.png)
Cuando hago el open app del restapi me dice que sucede un applicatio error
![image](https://user-images.githubusercontent.com/79645666/165732391-fabefe74-602c-4849-9b6f-259f8a077d2c.png)
y que ejecute el comando "heroku logs --tail" el cual me da el siguiente resultado:
![herokuFail](https://user-images.githubusercontent.com/79645666/165731286-b9264d14-6a7f-4cf5-9445-541341159086.png)
Pensamos que el problema está en que no encuentra la dependencia marcada en la imagen a la hora de ejecutar el 'npm start'. Sino, la única otra opción que se nos ocurrió es que la aplicación no use el protocolo HTTPS, pero no sabemos tampoco como conseguir esto.
Aporto ahora captura de los scripts del package.json de restapi:
![image](https://user-images.githubusercontent.com/79645666/165731670-11c770ad-2c21-4e9d-80bc-686bef969ea0.png)
![image](https://user-images.githubusercontent.com/79645666/165731716-8eb1e29c-5df0-4aeb-a4af-3723b64efddb.png)

**Comment by pglez82** [comment]
El problema que veo aquí es que en Heroku estáis desplegando la versión de desarrollo, que ejecutáis con npm start, para esta versión hace falta la librería **ts-node-dev** que se encuentra en las devDependencies, es decir, que no se instalará en heroku por defecto (por eso os da el error).

Lo que tenéis que hacer es desplegar la versión optimizada que se crea con `npm run build` y se ejecuta con `npm run prod`. Otra opción si por lo que sea queréis ejecutar la version de desarrollo en Heroku (no tiene mucho sentido pero por si acaso), es pasar la librería ts-node-dev a dependencies en lugar de devdependencies.

**Comment by AlejandroGalanFreire** [comment]
En principio en ambos sitios se nos ejecuta el npm run build, pero en el restapi se nos han duplicado todos los ficheros ts con extensión js, ¿eso es normal?
Algo así
![image](https://user-images.githubusercontent.com/79645666/165775493-cf173789-cf0b-4a77-9a0a-d0955a5299a4.png)

Por otro lado, para desplegar la versión optimizada, que se supone que tenemos que hacer una release del proyecto previamente?

**Comment by pglez82** [comment]
Acabo de ver que me he colado y las instrucciones que os he dado son para el webapp. En el restapi las cosas son un poco diferentes. Aquí `npm start` ejecuta `ts-node-dev ./server.ts`. ts-node-dev es una librería que permite la ejecución de archivos en typescript en node. Existe una alternativa para producción que es ts-node. Lo que yo haría sería probar a desplegar pasando la librería ts-node-dev a las dependencias normales y si os funciona, podéis probar a poner la librería ts-node en lugar de ts-node-dev que sería lo más correcto (y debería de funciona igual). Podríais configurar esto en el package.json del restapi para que cuando ejecutéis npm start se arranque la restapi con ts-node-dev y cuando se ejecute npm run prod se ejecute ts-node.

PD. Los archivos js que se han generado deberíais de borrarlos.

**Comment by pglez82** [comment]
Tranquilos que está cerca. Ahora os dice que os faltan unos paquetes de tipos que también tenéis en dev. No sé como estáis desplegando a heroku (con docker?) pero cambiad el `npm install` or npm ci que tengáis por `npm install -- dev`. Eso instalará también los paquetes de dev y al menos ese error ya no os lo dará.

**Comment by AlejandroGalanFreire** [comment]
Buenas otra vez Pablo, ya intente a realizar el npm install --dev y nada, incluso metí las tres dependencias que me dan error en las dependencias normales, pero me sigue dando el mismo error seguido de lo siguiente:
![image](https://user-images.githubusercontent.com/79645666/165894194-83d8be48-94db-407c-84f5-09e6c1dee3ac.png)
No se si estaré haciendo lo de npm install --dev o que podrá ser.

**Comment by AlejandroGalanFreire** [comment]
Y en principio estoy desplegando directamente desde Heroku CLI. Supongo que para usar Docker tendria que hacerlo desde el workflow, ¿verdad?

**Comment by pglez82** [comment]
Con docker yo diría que es más fácil, dado que si te funcionan las imágenes en local, te funcionarán en heroku. Es así como lo hacíamos el año pasao 

https://github.com/arquisoft/radarin_0

Este error te está diciendo que no encuentra un módulo, que he visto que está en:

https://github.com/Arquisoft/dede_es2a/blob/master/restapi/modules/cloudinary.ts

No sé si la mayúscula tendrá algo que ver. Aquí me pierdo un poco porque no conozco vuestro código. ¿Os funciona en local? Igual el tema de la mayúscula funciona en windows que no es case sensitive.

**Comment by AlejandroGalanFreire** [comment]
Si, las imágenes de docker nos funcionan en local, así que probare cuando salga de clases y te comento. En cuanto a lo de la mayúscula, en local no da problemas pero pueder ser que sea eso.

**Comment by pglez82** [comment]
en local usais Windows y en remoto es Linux. No sé si será eso pero yo lo pondría bien por si acaso.

**Comment by AlejandroGalanFreire** [comment]
Te comento un poco lo que hicimos ayer Pablo. En primer lugar intentamos desplegarlo con docker desde el workflow, y nos dio todo con el tick verde ✅. El problema es que al buscar la URL desde el navegador nos daba "application error" en ambas aplicaciones, es decir, tanto en webapp como en restapi. El error de restapi puede que sea debido a la mayúscula de Cloudinary, lo que nos extraña ahora es la parte del frontend, se ejecuta no se por qué npm run dev y además nos da un problema de memoria al parecer. Te adjunto captura:
![image](https://user-images.githubusercontent.com/79645666/166100888-4349badb-e5c2-430b-8d29-4d91e06e30f0.png)
Por otro lado, no se muy bien a que te refieres con que en local uso Windows y en remoto Linux.

**Comment by pglez82** [comment]
Bueno, Heroku tiene unos límites de memoria bajos en las instancias gratuitas pero que deberían de ser suficientes. El principal problema que veo es que estáis desplegando la versión de desarrollo en lugar de la versión optimizada por lo que esto consumiará más memoria si cabe.

Realmente no sé como puedo ayudaros aquí. Necesitaría más información de como estáis haciendo el despliegue (github actions?), también saber si os funciona en local usando docker, etc.


"Por otro lado, no se muy bien a que te refieres con que en local uso Windows y en remoto Linux." 

me refería a que en local estaréis usando windows que no es case sensitive, y cuando desplegáis, las máquinas en las que corre heroku y github actions son máquinas linux, que si son case sensitive.

**Comment by UO271728** [comment]
Buenas, hemos conseguido por fin desplegar la aplicación en heroku pero el problema que tenemos ahora es que cada ruta de la aplicación nos aparece lo siguiente:
![image](https://user-images.githubusercontent.com/71430118/166166213-27fec59f-c082-4048-a515-30b6a0e582f4.png).
Hemos visto que en el foro había el mismo error y propusieron una solución para arreglar el tema pero aun así seguimos con el problema y no entendemos porque sucede. 
![image](https://user-images.githubusercontent.com/71430118/166166433-95033aa7-c8f2-4af6-ba1b-bf4fc914a7c4.png)

**Comment by pglez82** [comment]
Me acabo de clonar vuestro respositorio y después de hacer `npm run build` y `npm run prod`, y al menos a mi la aplicación no se muestra en el navegador (sale una página en blanco). Ni por http ni por https. También he construido la imagen de docker y me pasa lo mismo. Mi pregunta es, ¿habéis comprobado que todo funciona en local, especialmente con docker, antes de desplegar?

**Comment by UO271728** [comment]
Buenos días, ese error ya está solucionado y es que para la release deje en corsOptions solamente la url de heroku pero añadiendo lo siguiente me funciona con docker y en local.
![image](https://user-images.githubusercontent.com/71430118/166210715-1d17a7ad-33ac-4e89-87f8-f72b26a53456.png)

**Comment by pglez82** [comment]
Lo que tenéis que entender es que os estoy intentando ayudar sin ninguna información. Si creáis un issue hace falta documentar las cosas lo suficiente para que yo pueda reproducir el problema y ver lo que pasa. A ciegas me es imposible hacer nada, y menos cuando después de un problema viene otro. Pensad que yo no he desarrollado vuestro proyecto y por tanto conozco exclusivamente lo que veo en vuestro repositorio y en esta issue.

Resumiendo, no se que quiere decir que está solucionado. Yo lo que veo en master es lo mismo que yo he probado en mi ordenador y que entiendo que se está desplegando a través del sistema de CI.

**Comment by uo276514** [comment]
🔥🔥🔥💣
