### ISSUE TITLE
Trabajo realizado prototipo Mario

### ISSUE THREAD

**Issue by mariolada** [Arquisoft/dede_es2a#61]
La parte principal del trabajo que he realizado es el carrito y la colocación de elementos en la web principal. También he corregido las partes de la documentación que nos había revisado el profesor
- https://github.com/Arquisoft/dede_es2a/issues/50
- https://github.com/Arquisoft/dede_es2a/issues/48
- https://github.com/Arquisoft/dede_es2a/issues/53
- https://github.com/Arquisoft/dede_es2a/issues/42
- https://github.com/Arquisoft/dede_es2a/issues/33
- https://github.com/Arquisoft/dede_es2a/issues/25
- https://github.com/Arquisoft/dede_es2a/issues/20
- Realizado Diagrama de secuencia de la compra de un producto

**Comment by uo276514** [comment]
✅
