### ISSUE TITLE
Trabajo realizado prototipo Alejandro

### ISSUE THREAD

**Issue by AlejandroGalanFreire** [Arquisoft/dede_es2a#64]
He realizado junto con mi compañero Rafa la creación y conexión de la base de datos con el backend.
También nos encargamos de la conexión backend con frontend visualizando los objetos de la base de datos en el navegador. Para ello modificamos la primera versión del carrito. Las imágenes las cargamos desde URLs de internet.
Todas las issues en las que me vi involucrado son las siguientes:
#30 
#32 
#35 
#43 
#53 
#58
#63

**Comment by uo276514** [comment]
✅
